// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCohIrpQOeBiReDmlTLsmKyS-kJEPZuKRw',
    appId: '1:290757325801:web:c68e4aea4d18d962e35178',
    messagingSenderId: '290757325801',
    projectId: 'ecommrceapp-e35a9',
    authDomain: 'ecommrceapp-e35a9.firebaseapp.com',
    databaseURL: 'https://ecommrceapp-e35a9-default-rtdb.firebaseio.com',
    storageBucket: 'ecommrceapp-e35a9.appspot.com',
    measurementId: 'G-WT1FXVQH6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXPWB7VeT47fTqR7b8rIVbOsvViMQOH3c',
    appId: '1:290757325801:android:b81ad6c7b743c1b7e35178',
    messagingSenderId: '290757325801',
    projectId: 'ecommrceapp-e35a9',
    databaseURL: 'https://ecommrceapp-e35a9-default-rtdb.firebaseio.com',
    storageBucket: 'ecommrceapp-e35a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0itzEEloACq_2_SSxHrymKEhQ0RaZxuk',
    appId: '1:290757325801:ios:47750120a0f93386e35178',
    messagingSenderId: '290757325801',
    projectId: 'ecommrceapp-e35a9',
    databaseURL: 'https://ecommrceapp-e35a9-default-rtdb.firebaseio.com',
    storageBucket: 'ecommrceapp-e35a9.appspot.com',
    iosBundleId: 'com.Garroudji.ecomarceAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0itzEEloACq_2_SSxHrymKEhQ0RaZxuk',
    appId: '1:290757325801:ios:47750120a0f93386e35178',
    messagingSenderId: '290757325801',
    projectId: 'ecommrceapp-e35a9',
    databaseURL: 'https://ecommrceapp-e35a9-default-rtdb.firebaseio.com',
    storageBucket: 'ecommrceapp-e35a9.appspot.com',
    iosBundleId: 'com.Garroudji.ecomarceAppProject',
  );
}
